---
- name: Install homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: "/usr/local/bin/brew"
    
- name: Install tap {{ item }}
  homebrew_tap:
    name: "{{ item }}"
  with_flattened:
    - "{{ d_homebrew_tap }}"
    - "{{ homebrew_tap }}"

- name: Install {{ item.name }} via homebrew
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ d_homebrew }}"
    - "{{ homebrew }}"
    
- name: Install cask {{ item.name }} via homebrew
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ d_homebrew_cask }}"
    - "{{ homebrew_cask }}"
