---
- name: Install homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: Install Xcode CLT
  shell: xcode-select --install
  args:
    creates: /Library/Developer/CommandLineTools/usr/bin/gcc
