d_pip:
  - name: "ansible"
    state: "present"
  - name: "psycopg2"
    state: "present"
  - name: "virtualenv"
    state: "present"
  - name: "boto"
    state: "present"
  - name: "requests"
    state: "present"
  - name: "boto3"
    state: "present"
