---
- name: Install {{ item.name }} pip package in root python
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_flattened:
    - "{{ d_pip }}"
    - "{{ pip }}"
  when: item.venv is undefined
  become: true 

- name: Install {{ item.name }} pip package into virtualenv
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    virtualenv: "{{ item.venv }}"
  with_flattened:
    - "{{ d_pip }}"
    - "{{ pip }}"
  when: item.venv is defined
