---
- name: setup .vim directories
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
    mode: 0755  
- name: Insatll vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    mode: 0755

- name: Deploy custom .vimrc file
  template:
    src: templates/dot_vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0755
    backup: yes  
